"""add_connection_settings

Revision ID: 8e2fcc1feb5e
Revises: 559bbcb91aad
Create Date: 2025-03-05 14:56:29.614325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2fcc1feb5e'
down_revision: Union[str, None] = '559bbcb91aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_db_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'CRON', name='scheduletype'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('connection_state', sa.JSON(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_settings')
    # ### end Alembic commands ###
