"""add destinations & rename connections

Revision ID: 9eadb457b0ce
Revises: e6ec600f7dcc
Create Date: 2025-03-06 15:21:41.971584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eadb457b0ce'
down_revision: Union[str, None] = 'e6ec600f7dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('dataset', sa.String(length=100), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('folder_path', sa.String(length=255), nullable=True),
    sa.Column('hmac_key', sa.String(length=255), nullable=False),
    sa.Column('hmac_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_db_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'CRON', name='scheduletype'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connection_state', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_db_id')
    )
    op.drop_table('connection_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_db_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_type', postgresql.ENUM('MANUAL', 'CRON', name='scheduletype'), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('connection_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_databases.id'], name='connection_settings_source_db_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='connection_settings_pkey'),
    sa.UniqueConstraint('source_db_id', name='connection_settings_source_db_id_key')
    )
    op.drop_table('connections')
    op.drop_table('destinations')
    # ### end Alembic commands ###
