"""alter_connection_settings

Revision ID: e6ec600f7dcc
Revises: 8e2fcc1feb5e
Create Date: 2025-03-05 15:18:35.954852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ec600f7dcc'
down_revision: Union[str, None] = '8e2fcc1feb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_settings', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('connection_settings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('connection_settings', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.add_column('connection_settings', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_settings', 'next_run_at')
    op.drop_column('connection_settings', 'last_run_at')
    op.drop_column('connection_settings', 'is_active')
    op.drop_column('connection_settings', 'name')
    # ### end Alembic commands ###
