"""add_schema_version_table

Revision ID: f3fd2813dd0f
Revises: 471e4447ec94
Create Date: 2025-03-05 13:14:18.981984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fd2813dd0f'
down_revision: Union[str, None] = '471e4447ec94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_db_id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_versions')
    # ### end Alembic commands ###
